version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: Scripts/installnginx.sh
  AfterInstall:
    - location: Scripts/startnginx.sh
      timeout: 180
